### ISSUE TITLE
AI21SemanticTextSplitter returning 404 in version < 1 and missing in version 1.0.0

### ISSUE THREAD

**Issue by MirkovicDragan** [langchain-ai/langchain-ai21#16]
I started getting this response while trying to use AI21SemanticTextSplitter -> Failed with http status code: 404 (AI21APIError). Details: {"detail":"Not Found"}. Version of the package was 0.1.7.

After that I upgraded my package from 0.1.7 to 1.0.0, that caused me issue with the import of the splitter from the package.
Now I am getting ImportError: cannot import name 'AI21SemanticTextSplitter' from 'langchain_ai21'. It looks like splitter is not part of the library anymore?

Do you know how can I still use it, what is the alternative.

**Comment by dickreuter** [comment]
Just wrote to AI21, and they said the below. Don't really have any solution how this can be used with langchain. Let me know if you find out.

Hello,
Thank you for contacting AI21 Support.
The TSM you mention was taken out of service last week on 11/14. A few weeks ago an email was sent out to users of the J2 models and TSM's of the last couple months notifying them these models and their associated API endpoints would be taken offline on 11/14. Below is a copy of this email:
You’re receiving this email because you’re using one or more legacy API endpoints that will be shut down on November 14, 2024.

For assistance in transitioning, contact us at support@ai21.com.

Our legacy APIs will be discontinued on November 14th, 2024 in favor of our new Jamba models. This means that any call to the models listed below will no longer be accessible starting from November 14th, 2024, resulting in an error message.

To avoid service disruption, we strongly encourage you to switch to our upgraded Jamba 1.5 series which offers improved performance and quality. For RAG engine users, see conversational RAG.

What are we discontinuing?

Jamba Instruct - Jamba Instruct, a prior version, will be discontinued in favor of our Jamba 1.5 series.
Jurassic-2 - All endpoints for the Jurassic-2 family of models
Task-Specific Models (TSMs) - All Task-Specific Model endpoints
- Contextual Answers
- Semantic Search
- Embeddings
- Paraphrase
- Grammatical Error Corrections
- Text Improvements
- Summarize
- Text Segmentations
- Custom models
- Datasets
If you'd like to try out our Jamba 1.5 models, you can access it in our [Studio](https://studio.ai21.com/v2/chat) or through API: https://docs.ai21.com/reference/jamba-15-api-ref
Regards,
Nick @AI21

**Comment by MirkovicDragan** [comment]
Thank you Nick.
